name: Build DevOS ISO (Testing with Releng Profile)

on:
  push:
    branches: [ "arch" ]
  workflow_dispatch:

jobs:
  build-and-release-testing:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ISO using Releng Profile
        run: |
          docker run --rm --privileged -v ${{ github.workspace }}:/data archlinux:latest \
          /bin/bash -c "
            set -e

            echo '--- Preparing Environment ---'
            pacman -Syu --noconfirm archiso

            echo '--- Copying official releng profile ---'
            cp -a /usr/share/archiso/configs/releng/. /data/archiso

            echo '--- Modifying releng profile for DevOS ---'
            # 1. Меняем метку диска
            sed -i 's/iso_label=\"ARCH_\"/iso_label=\"DEVOS\"/g' /data/archiso/profiledef.sh
            sed -i 's/archisolabel=\${iso_label}/archisolabel=DEVOS/g' /data/archiso/grub/grub.cfg
            sed -i 's/archisolabel=\${iso_label}/archisolabel=DEVOS/g' /data/archiso/syslinux/archiso_sys.cfg

            # 2. Добавляем наш репозиторий и пакеты. Убираем ненужный xorg-xinit.
            echo -e \"\n[devos-repo]\nSigLevel = Optional TrustAll\nServer = file:///data/repo\" >> /data/archiso/pacman.conf
            echo -e \"\n# DevOS Packages\ncalamares\ndevos-tools-core\ngdm\ngnome-shell\ngnome-terminal\ngnome-control-center\nnautilus\nfirefox\n\" >> /data/archiso/packages.x86_64

            # --- !!! НОВАЯ, ПРАВИЛЬНАЯ И ФИНАЛЬНАЯ МАГИЯ !!! ---
            echo '--- Customizing Live Environment for GDM Auto-Login ---'

            # 3. Создаем конфигурацию для GDM, чтобы он автоматически логинил root
            mkdir -p /data/archiso/airootfs/etc/gdm
            echo -e '[daemon]\nAutomaticLoginEnable=true\nAutomaticLogin=root' > /data/archiso/airootfs/etc/gdm/custom.conf

            # 4. Включаем сервисы GDM и NetworkManager
            mkdir -p /data/archiso/airootfs/etc/systemd/system/multi-user.target.wants
            ln -sf /usr/lib/systemd/system/gdm.service /data/archiso/airootfs/etc/systemd/system/multi-user.target.wants/gdm.service
            ln -sf /usr/lib/systemd/system/NetworkManager.service /data/archiso/airootfs/etc/systemd/system/multi-user.target.wants/NetworkManager.service

            # 5. Создаем .desktop файл для авто-запуска Calamares
            mkdir -p /data/archiso/airootfs/root/.config/autostart
            mkdir -p /data/archiso/airootfs/root/Desktop
            echo -e '[Desktop Entry]\nName=Install DevOS\nExec=sudo calamares\nType=Application\nIcon=system-installer' > /data/archiso/airootfs/root/Desktop/install.desktop
            cp /data/archiso/airootfs/root/Desktop/install.desktop /data/archiso/airootfs/root/.config/autostart/

            echo '--- Creating local repository database ---'
            repo-add /data/repo/devos-repo.db.tar.gz /data/repo/*.pkg.tar.zst

            echo '--- Building ISO Image from modified releng profile ---'
            mkarchiso -v -w /tmp/archiso-work -o /data/out /data/archiso
          "

      - name: Upload ISO to a new Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test-build-${{ github.run_number }}
          name: "Test Build ${{ github.run_number }} (arch branch)"
          body: |
            Автоматическая тестовая сборка из ветки `arch` с использованием профиля `releng`.
            Commit: `${{ github.sha }}`
          files: |
            out/archlinux-*.iso
          prerelease: true