name: Build DevOS ISO (Testing with Releng Profile)

on:
  push:
    branches: [ "arch" ]
  workflow_dispatch:

jobs:
  build-and-release-testing:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ISO using Releng Profile
        run: |
          docker run --rm --privileged -v ${{ github.workspace }}:/data archlinux:latest \
          /bin/bash -c "
            set -e

            echo '--- [1/6] Preparing Environment ---'
            pacman -Syu --noconfirm archiso

            echo '--- [2/6] Copying and Modifying Profile ---'
            cp -a /usr/share/archiso/configs/releng/. /data/archiso
            
            sed -i 's/iso_label=\"ARCH_\"/iso_label=\"DEVOS\"/g' /data/archiso/profiledef.sh
            
            # Добавляем наш репозиторий и пакеты
            echo -e \"\n[devos-repo]\nSigLevel = Optional TrustAll\nServer = file:///data/repo\" >> /data/archiso/pacman.conf
            echo -e \"\n# DevOS Packages\ncalamares\ndevos-tools-core\ngdm\ngnome-shell\ngnome-terminal\ngnome-control-center\nnautilus\nfirefox\nNetworkManager\" >> /data/archiso/packages.x86_64

            # --- [3/6] УДАЛЕНЫ СТАРЫЕ, НЕСТАБИЛЬНЫЕ НАСТРОЙКИ ---
            # Мы больше не создаем симлинки и .desktop файлы вручную.
            # Вместо этого мы будем использовать кастомный скрипт.

            echo '--- [4/6] Creating local repository database ---'
            repo-add /data/repo/devos-repo.db.tar.gz /data/repo/*.pkg.tar.zst

            echo '--- [5/6] Building base ISO (this installs packages into airootfs) ---'
            # На этом этапе mkarchiso создает директорию airootfs и устанавливает туда все пакеты
            mkarchiso -v -w /tmp/archiso-work -o /data/out /data/archiso
            
            # --- [6/6] ИДЕАЛЬНОЕ МЕСТО ДЛЯ НАШЕГО СКРИПТА ---
            # Директория airootfs уже создана и наполнена пакетами.
            # Теперь мы можем безопасно войти в нее и настроить сервисы.
            echo '--- [6/6] Customizing Live Environment Autostart ---'
            chmod +x /data/configure_autostart.sh
            /data/configure_autostart.sh

            echo '--- Build process completed ---'
          "

      - name: Upload ISO to a new Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test-build-${{ github.run_number }}
          name: "Test Build ${{ github.run_number }} (arch branch)"
          body: |
            Автоматическая тестовая сборка из ветки `arch`.
            Запускается Calamares вместо GDM.
            Commit: `${{ github.sha }}`
          files: |
            out/*.iso # Более надежный путь к файлу
          prerelease: true