name: Build DevOS Packages and ISO

on:
  push:
    branches: [ "main" ]
    paths:
      - 'packages/**'
      - 'archiso/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ISO with Custom Packages
        run: |
          docker run --rm --privileged -v ${{ github.workspace }}:/data archlinux:latest \
          /bin/bash -c "
            pacman -Syu --noconfirm base-devel git archiso;
            useradd builder -m;
            echo 'builder ALL=(ALL) NOPASSWD: /usr/bin/pacman' >> /etc/sudoers;
            chown -R builder:builder /data;

            su builder -c '
              cd /data/packages && \
              for dir in */ ; do
                if [ -f \"\${dir}PKGBUILD\" ]; then
                  cd \"\${dir}\" && \
                  makepkg --noconfirm -scf && \
                  mv *.pkg.tar.zst /data/repo/ && \
                  cd .. ;
                fi
              done
            '
            
            curl -L -o /data/repo/calamares.pkg.tar.zst \"https://mirror.alpix.eu/endeavouros/repo/endeavouros/x86_64/calamares-3.3.6-1-x86_64.pkg.tar.zst\"
            
            repo-add /data/repo/devos-repo.db.tar.gz /data/repo/*.pkg.tar.zst

            cd /data/archiso;
            
            mkarchiso -v -w /tmp/archiso-work -o /data/out .
          "
      - name: Restore workspace ownership
        run: sudo chown -R $(whoami):$(whoami) .

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: DevOS-ISO
          path: archiso/out/devos-*.iso