name: Build DevOS ISO (Testing)

on:
  push:
    branches: [ "arch" ]
  workflow_dispatch:

jobs:
  build-and-release-testing:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ISO with Diagnostics
        run: |
          docker run --rm --privileged -v ${{ github.workspace }}:/data archlinux:latest \
          /bin/bash -c "
            set -e # Прерываем выполнение при любой ошибке

            echo '--- Preparing Environment ---'
            pacman -Syu --noconfirm archiso

            echo '--- Creating local repository database ---'
            if [ -z \"\$(ls -A /data/repo/*.pkg.tar.zst 2>/dev/null)\" ]; then
              echo \"WARNING: No package files found in /data/repo/. Building with official packages only.\"
              mkdir -p /data/repo
              repo-add /data/repo/devos-repo.db.tar.gz
            else
              repo-add /data/repo/devos-repo.db.tar.gz /data/repo/*.pkg.tar.zst
            fi

            # --- !!! ДИАГНОСТИЧЕСКИЙ ШАГ !!! ---
            # Мы распечатываем содержимое ключевых файлов, чтобы убедиться,
            # что checkout скачал правильные версии.
            echo '--- Verifying bootloader configs inside container ---'
            echo '--- Contents of profiledef.sh: ---'
            cat /data/archiso/profiledef.sh | grep 'iso_label'
            echo '--- Contents of syslinux.cfg: ---'
            cat /data/archiso/syslinux/syslinux.cfg | grep 'APPEND'
            echo '--- Contents of archiso-x86_64.conf: ---'
            cat /data/archiso/efiboot/loader/entries/archiso-x86_64.conf | grep 'options'
            echo '--- Verification complete ---'


            echo '--- Building ISO Image ---'
            mkarchiso -v -w /tmp/archiso-work -o /data/out /data/archiso
          "

      - name: Upload ISO to a new Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test-build-${{ github.run_number }}
          name: "Test Build ${{ github.run_number }} (arch branch)"
          body: |
            Автоматическая тестовая сборка из ветки `arch`.
            Commit: `${{ github.sha }}`
          files: |
            out/devos-*.iso
          prerelease: true